sudo: false
language: node_js
node_js:
- "0.10"
- "0.12"
- "4"
- "5"
notifications:
  email: false
  slack:
    secure: ZXzgXYoby8pgSbCnxhEt1VRHxX4PQvTr0SZhsKp4EQQm7BOmhrwMiUoTr89q8mLVJnmla7xQQ1si5V5SdI5wL/aDjPLvYmUUHcjt/iJAAUuoqlrLXqBHJR+9FONWNbFZCIfYKgQ5etHFDbdCEu4KI+4YhEVLUf8eQX3WZcMjT5A=
after_script:
- cat coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token:
      secure: VSkXYZm2dfS/2gU+jC9YV4/igRhJq5xsir8Td4IVDOvr2++ejFaFaB1U4ElohOvXikPyBYMDds1IOaAXtBtcEgSEjucrzqsK82aiut5ux0PKqwciusHQZNej4SHN2lwdXmF/zqvZiBFxMJRuKZ4ChixVzNkskj13qGDwW+y/l2w=
