language: node_js
node_js:
  - 0.10
  - 0.11
notifications:
  email: false
after_script:
  - cat coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token:
      secure: VSkXYZm2dfS/2gU+jC9YV4/igRhJq5xsir8Td4IVDOvr2++ejFaFaB1U4ElohOvXikPyBYMDds1IOaAXtBtcEgSEjucrzqsK82aiut5ux0PKqwciusHQZNej4SHN2lwdXmF/zqvZiBFxMJRuKZ4ChixVzNkskj13qGDwW+y/l2w=
